import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./SessionProvider";
import Sidebar from "./components/layout/Sidebar";
import FollowBar from "./components/layout/Followbar";
import Modal from "./components/Modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl ">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />

                <div
                  className="
                col-span-3
                lg:col-span-2
                border-x-[1px]
                border-neutral-800 
                "
                >
                  {children}
                </div>
                <FollowBar />
              </div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
